import '../styles/globals.css';
import { cn } from '@/utils/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'debug-screens flex min-h-screen w-full max-w-screen-xl flex-col bg-zinc-950 px-24 py-10 text-sm text-zinc-50 antialiased',
          inter.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
