import '../styles/globals.css';
import PageWrapper from '@/components/PageWrapper';
import { cn } from '@/utils/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Lumosent',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'debug-screens bg-zinc-950 text-sm text-zinc-50 antialiased',
          inter.className
        )}
      >
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}
